package com.scivicslab.coderaptor.index;

import com.scivicslab.coderaptor.model.ProjectInfo;
import jakarta.enterprise.context.ApplicationScoped;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Reads a project directory and produces a {@link ProjectInfo} by inspecting
 * well-known indicator files (pom.xml, build.gradle, go.mod, Cargo.toml, …).
 *
 * <p>Detection strategy: indicator-file based (O(1) per project, no directory walk).
 * The first matching rule wins; priority order is documented in each detect* method.
 *
 * <p>Shared by {@link com.scivicslab.coderaptor.service.IndexService} (index build)
 * and {@link com.scivicslab.coderaptor.resource.ProjectsResource} (REST listing).
 */
@ApplicationScoped
public class ProjectInfoReader {

    private static final Pattern GROUP_ID    = Pattern.compile("<groupId>([^<]+)</groupId>");
    private static final Pattern ARTIFACT_ID = Pattern.compile("<artifactId>([^<]+)</artifactId>");
    private static final Pattern VERSION     = Pattern.compile("<version>([^<]+)</version>");

    /**
     * Reads project metadata from the given directory.
     *
     * @param projectDir directory to inspect (must exist)
     * @return populated {@link ProjectInfo}
     */
    public ProjectInfo read(Path projectDir) {
        String name       = projectDir.getFileName().toString();
        String buildSystem = detectBuildSystem(projectDir);
        String language    = detectLanguage(projectDir, buildSystem);
        String compiledDocs = detectCompiledDocs(projectDir, language);

        boolean isMaven   = "Maven".equals(buildSystem);
        String groupId    = "";
        String artifactId = "";
        String version    = "";

        if (isMaven) {
            try {
                byte[] bytes = Files.readAllBytes(projectDir.resolve("pom.xml"));
                String pom = new String(bytes, java.nio.charset.StandardCharsets.UTF_8);
                String head = pom.length() > 3000 ? pom.substring(0, 3000) : pom;
                groupId    = firstMatch(GROUP_ID,    head);
                artifactId = firstMatch(ARTIFACT_ID, head);
                version    = firstMatch(VERSION,     head);
            } catch (IOException ignored) {}
        }

        return new ProjectInfo(name, language, buildSystem, compiledDocs,
                groupId, artifactId, version, isMaven);
    }

    // ── Build system detection ────────────────────────────────────────────────
    //
    // Priority: most-specific indicator first.
    //
    // Returned values are used as-is in the UI tag and Lucene index.

    private static String detectBuildSystem(Path dir) {
        if (exists(dir, "pom.xml"))             return "Maven";
        if (exists(dir, "build.gradle.kts"))    return "Gradle";
        if (exists(dir, "build.gradle"))        return "Gradle";
        if (exists(dir, "go.mod"))              return "Go Modules";
        if (exists(dir, "Cargo.toml"))          return "Cargo";
        if (exists(dir, "pyproject.toml"))      return "pyproject";
        if (exists(dir, "setup.py"))            return "pip";
        if (exists(dir, "package.json"))        return "npm";
        if (exists(dir, "CMakeLists.txt"))      return "CMake";
        // Autotools (autoconf/automake): the source files are the real indicator.
        // The top-level Makefile is generated by ./configure, so a project may have
        // only Makefile.am / configure.ac before it has ever been configured.
        if (exists(dir, "configure.ac")
                || exists(dir, "configure.in")
                || exists(dir, "Makefile.am"))  return "Autotools";
        if (exists(dir, "Makefile"))            return "Make";
        return "";
    }

    // ── Language detection ────────────────────────────────────────────────────
    //
    // Derived from the build system whenever unambiguous; otherwise inspects
    // additional indicator files (no directory walk needed).

    private static String detectLanguage(Path dir, String buildSystem) {
        return switch (buildSystem) {
            case "Maven", "Gradle" -> {
                // Could be Kotlin or Groovy, but Java is by far the most common
                if (exists(dir, "src/main/kotlin") || exists(dir, "build.gradle.kts"))
                    yield "Kotlin";
                yield "Java";
            }
            case "Go Modules"  -> "Go";
            case "Cargo"       -> "Rust";
            case "pyproject", "pip" -> "Python";
            case "npm" -> {
                // TypeScript if tsconfig.json is present
                if (exists(dir, "tsconfig.json")) yield "TypeScript";
                yield "JavaScript";
            }
            case "CMake", "Autotools", "Make" -> "C/C++";
            default -> {
                // No recognized build system — sniff by well-known files
                if (exists(dir, "go.sum"))           yield "Go";
                if (exists(dir, "requirements.txt")) yield "Python";
                if (exists(dir, "tsconfig.json"))    yield "TypeScript";
                yield "";
            }
        };
    }

    // ── Compiled docs detection ───────────────────────────────────────────────
    //
    // Returns a project-relative path to the compiled docs root directory,
    // or an empty string if no compiled docs are found.
    //
    // Checked paths (in order):
    //   Java/Maven  : target/site/apidocs   (mvn javadoc:javadoc)
    //   Rust        : target/doc            (cargo doc)
    //   Python/Sphinx: docs/_build/html
    //   Python/MkDocs: site
    //   JavaScript  : docs
    //   C/C++/Doxygen: doc/html, docs/html, html

    private static String detectCompiledDocs(Path dir, String language) {
        // Language-specific paths first (faster short-circuit)
        if ("Java".equals(language) || "Kotlin".equals(language)) {
            if (isDir(dir, "target/site/apidocs")) return "target/site/apidocs";
        }
        if ("Rust".equals(language)) {
            if (isDir(dir, "target/doc")) return "target/doc";
        }
        if ("C/C++".equals(language)) {
            // Doxygen HTML output: OUTPUT_DIRECTORY + HTML_OUTPUT in the Doxyfile.
            // Common combinations are doc/html, docs/html, or a bare html.
            if (isDir(dir, "doc/html"))  return "doc/html";
            if (isDir(dir, "docs/html")) return "docs/html";
            if (isDir(dir, "html"))      return "html";
        }
        if ("Python".equals(language)) {
            if (isDir(dir, "docs/_build/html")) return "docs/_build/html";
            if (isDir(dir, "site"))             return "site";
        }
        if ("JavaScript".equals(language) || "TypeScript".equals(language)) {
            if (isDir(dir, "docs")) return "docs";
        }
        // Generic fallbacks (language unknown or mixed projects)
        if (isDir(dir, "target/site/apidocs")) return "target/site/apidocs";
        if (isDir(dir, "target/doc"))          return "target/doc";
        if (isDir(dir, "docs/_build/html"))    return "docs/_build/html";
        return "";
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private static boolean exists(Path dir, String relative) {
        return Files.exists(dir.resolve(relative));
    }

    private static boolean isDir(Path dir, String relative) {
        return Files.isDirectory(dir.resolve(relative));
    }

    private static String firstMatch(Pattern p, String text) {
        Matcher m = p.matcher(text);
        return m.find() ? m.group(1).trim() : "";
    }
}
